// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package mini_wire

// Injectors from wire.go:

func NewMissionImpl(name string) *Mission {
	monster := NewMonster(name)
	hero := NewHero(name)
	mission := NewMission(monster, hero)
	return mission
}
